version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout

      # Install Firebase tools
      - run:
          name: Install Firebase Tools
          command: npm install -g firebase-tools

      # Authenticate with Firebase using service account key (using temporary file)
      - run:
          name: Create Temporary Key File
          command: |
            KEY_FILE=$(mktemp)
            echo ${GOOGLE_APPLICATION_CREDENTIALS} | base64 --decode > $KEY_FILE
            echo "Created temporary key file: $KEY_FILE"

      - run:
          name: Authenticate with Firebase
          command: firebase deploy --only hosting --token $KEY_FILE

      # (Optional) Delete temporary key file
      - run:
          name: Clean Up Temporary Key File
          command: rm -f $KEY_FILE

workflows:
  deploy_firebase_website:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main


