version: 2.1
jobs:
  build:
    docker:
       - image: cimg/node:21.6.2

    steps:
      - checkout

      # Install Firebase tools
      - run:
          name: Install Firebase Tools
          command: npm install -g firebase-tools

      # Authenticate with Firebase
      - run:
          name: Authenticate with Firebase
          command: firebase login:ci --interactive

      # Build and deploy to Firebase Hosting
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting --token $FIREBASE_TOKEN

workflows:
  deploy_firebase_website:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

