version: 2.1

jobs:
  deploy_to_firebase:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Update and Install Firebase CLI
          command: |
            npm install -g firebase-tools@latest
            firebase --version  # Check the version to ensure it's updated
      - run:
          name: Firebase Login
          command: firebase login --no-interactive --token ${FIREBASE_TOKEN}
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting

workflows:
  deploy:
    jobs:
      - deploy_to_firebase:
          filters:
            branches:
              only:
                - main
