version: 2.1

jobs:
  deploy_to_firebase:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools
      # Use CircleCI secrets to securely store and access Firebase token
      - run:
          name: Retrieve Firebase Token
          command: |
            FIREBASE_TOKEN=$(circleci secrets get FIREBASE_TOKEN)
      - run:
          name: Firebase Login (using retrieved token)
          command: firebase deploy --token "$FIREBASE_TOKEN"
      - run:
          name: Deploy to Firebase Hosting (using retrieved token)
          command: firebase deploy --only hosting --token "$FIREBASE_TOKEN"

workflows:
  deploy:
    jobs:
      - deploy_to_firebase:
          filters:
            branches:
              only:
                - main

