version: 2.1

jobs:
  deploy_to_firebase:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools
      - run:
          name: Firebase Login
          command: firebase login --no-interactive --token 1//03RytUuQRR_IGCgYIARAAGAMSNwF-L9Ir7PPTzsrD746iL2z0tYjyn9C8d6Z0icS3ppPJ7-ehflSE9V8UFERQXaj9t6_k6UpBeCw
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting

workflows:
  deploy:
    jobs:
      - deploy_to_firebase:
          filters:
            branches:
              only:
                - main
